require('lazy').setup({
  { import = 'plugins.alpha' },
  { import = 'plugins.autopairs' },
  { import = 'plugins.bufdel' },
  { import = 'plugins.colorizer' },
  { import = 'plugins.comment' },
  { import = 'plugins.completition' },
  { import = 'plugins.dap' },
  { import = 'plugins.diffview' },
  { import = 'plugins.dressing' },
  { import = 'plugins.fugitive' },
  { import = 'plugins.git-messenger' },
  { import = 'plugins.gitsigns' },
  { import = 'plugins.indent' },
  require 'plugins.heirline',
  { import = 'plugins.lsp' },
  { import = 'plugins.luasnip' },
  { import = 'plugins.markdown' },
  { import = 'plugins.neo-tree' },
  { import = 'plugins.neoclip' },
  { import = 'plugins.notify' },
  { import = 'plugins.numb' },
  { import = 'plugins.repeat' },
  { import = 'plugins.rust' },
  { import = 'plugins.scrollview' },
  { import = 'plugins.spectre' },
  { import = 'plugins.surround' },
  { import = 'plugins.tabular' },
  { import = 'plugins.telescope' },
  { import = 'plugins.test' },
  { import = 'plugins.toggleterm' },
  { import = 'plugins.tokyonight' },
  { import = 'plugins.treesitter' },
  { import = 'plugins.trouble' },
  { import = 'plugins.which-key' },
  { import = 'plugins.zen-mode' },
})
