return {
  Align = require('plugins.heirline.modules.align'),
  Diagnostics = require('plugins.heirline.modules.diagnostics'),
  FileEncoding = require('plugins.heirline.modules.fileencoding'),
  FileFormat = require('plugins.heirline.modules.fileformat'),
  FileNameBlock = require('plugins.heirline.modules.filename').FileNameBlock,
  FileSize = require('plugins.heirline.modules.filesize'),
  FileType = require('plugins.heirline.modules.filetype'),
  Git = require('plugins.heirline.modules.git'),
  Ruler = require('plugins.heirline.modules.ruler'),
  ScrollBar = require('plugins.heirline.modules.scrollbar'),
  Space = require('plugins.heirline.modules.space'),
  Spell = require('plugins.heirline.modules.spell'),
  ViMode = require('plugins.heirline.modules.vimode'),
}
